backend:
  name: github
  repo: ваш-username/имя-репозитория
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "Настройки сайта"
    folder: "content/settings"
    create: false
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Описание", name: "description", widget: "string" }
  - name: "participants"
    label: "Участники"
    folder: "content/participants"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Имя", name: "name", widget: "string" }
      - { label: "Страна", name: "country", widget: "string" }
      - { label: "Статус", name: "status", widget: "select", options: ["confirmed", "live"] }
      - { label: "Информация", name: "info", widget: "text" }
      - { label: "Фото", name: "photo", widget: "image" }
